### ISSUE TITLE
Quickdraw takes a revenge shot after taking purely hull damage from a plasma torpedo

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#100]
![image](https://user-images.githubusercontent.com/8730661/37467562-f76eef16-2836-11e8-9231-988bc211e7dd.png)

![image](https://user-images.githubusercontent.com/8730661/37467569-fc672e66-2836-11e8-8c7f-3f623f77f6f1.png)

**Comment by Sleet01** [comment]
Yeah, this is probably due to Plasma Torp calling removeshield() no matter what... oh look, it is!  Seriously, I think I need to add "ALWAYS put braces around conditional statements!" to the top of the how-to doc.  In this case, because there were no braces, Plasma Torpedoes used the existence of shields on the target *to determine whether to log its shield removal ability*, but removed one shield even if no shields existed... triggering 'Quickdraw'.

I've added braces, which should fix the issue.  Fix will be in the next PR.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
