### ISSUE TITLE
trajectory simulator bomb off the map maybe crashes the game?

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#106]
![image](https://user-images.githubusercontent.com/8730661/37493119-37c632b6-287a-11e8-8176-a5ba850a2a3f.png)

My best blind guess as to what is happening (without seeing source code) is that the AI attempted to trajectory simulat a bomblet. The bomblet object didn't have a default location at initialization. the location that was given by the trajectory simulator was seen as an illegal location, and so the object was given no location. When it was time to draw said bomb, being given no location, the game read "undefined" as "probably 0" (maybe the sprite renderer assumes (undefined,undefined) is 0,0?), so drew the bomb there.  When it was time to actually calculate the bombs targets, it tried doing calculations against (undefined,undefined) and crashed

**Comment by Sleet01** [comment]
Looks like your read is spot on, although I'm not sure how a bomb could be dropped *or* simulated without getting a position assigned.  The .m member of all on-screen objects *should* be initialized as soon as the object is instantiated, but in this case the bomblet definitely does not have a .m member defined.  It's especially odd because I ran through several full games without seeing this issue previously.

**Comment by boredompwndu** [comment]
Replicating this was also stupidly impossible because it involved convincing an AI ship to simulate the bomb past a board edge. Is it possible that because the location had a negative coordinate, that everything panicked?

**Comment by Sleet01** [comment]
Found it!  Looks like there's an issue with the AI bomb location selection logic that, on rare occasions, returns an array with a single, undefined, entry.  It *should* be returning a single location object as a size-1 array, but somehow it's putting an un-initialized Object instance in there instead.  I should have this nailed down in a bit.

**Comment by Sleet01** [comment]
Fix is in Release; closing.
