### ISSUE TITLE
Kylo Ren (crew) not being used

### ISSUE THREAD

**Issue by reesim06** [baranidlo/bench#131]
Playing against a Decimator with Kylo Ren as crew. The AI never uses the Kylo action for ISYTDS.

In reality, I expect my opponent to use this every round he can.

**Comment by Sleet01** [comment]
There's a mechanism for giving the AI more detailed guidance on using action upgrades but as of right now this card doesn't have one of these functions implemented yet.  I haven't played Crew Kylo at all yet; can you define "every round he can"?  Would it take precedence over Focus and Evade?  Would it only be used when there's no viable shot for the Kylo-carrying ship this turn?

**Comment by reesim06** [comment]
On the rear admiral Decimator, he can turn a focus die into a critical. Plus a critical from Palpatine, he has a great chance to get a critical through. So the imperial player will use this for at least the first 2 engagements as he will assign blinded pilot to the opposing ship.

In a recent game I had, my Dash Rendar didn't shoot for the first 2 rounds of engagement, then was PS 0 on the third.

**Comment by boredompwndu** [comment]
The usual decision path for Kylo Crew is to definitely hand out blinded pilots on the first turns. ISYTDS is not reassigned until the card has been dealt. If the ship can avoid shots, that usually takes precedence over Kylo Crew. After Blinded Pilots, the other 3 crits are optional.

Damaged Cockpit: Does the opposing ship have more PS than the other ships in my list? If yes assign, else, no.

Shaken/Stunned Pilot These are mildly inconvenient and really only come into play if a ship has Regen mechanics like R2-D2, R5-P8, Gonk, Miranda, or pulsed ray shield. Otherwise it is better for the kylo crew player to be looking at other action options

**Comment by Sleet01** [comment]
Whelp, in addition to Kylo Ren needing AI guidance, the entirety of his entry had to be re-written.  I'm done with the re-write, I'll work on the AI part in a bit.

**Comment by Sleet01** [comment]
Fix is now in Release; closing.
