### ISSUE TITLE
TypeError: a is undefined (game stalled)

### ISSUE THREAD

**Issue by patof** [baranidlo/bench#141]
<img width="1371" alt="screen shot 2018-05-03 at 10 51 20" src="https://user-images.githubusercontent.com/10265795/39584333-292119e4-4ec0-11e8-9ece-ffa02f0b2b69.png">

**Comment by Sleet01** [comment]
To be honest, we haven't been exercising the team maneuvering code much in the past few months.  I'd guess that some of the other changes have broken something there, but I'll check it out after the next release.

**Comment by Sleet01** [comment]
Turns out one of my fixes for targeting docked ships was too simplistic, and introduced an error.  Only ships that have been docked once can have an "isdocked" attribute, but I was just blindly checking that attribute without first seeing if it actually existed.  This appears to only affect some abilities that check for enemies at a certain range (like Guri) but not firing weapons, so it wasn't immediately apparent.

This is fixed in my devel branch but I'd like to hold off on pushing it to Release until we have a few more fixes in place.  Please let me know if it's a critical bug affecting many more pilots, in which case I'll make it a priority hotfix instead.

**Comment by Sleet01** [comment]
This *should* be fixed in Release.  I'll close this bug, but if you see this particular issue again, please file a new issue.  Thanks!
