### ISSUE TITLE
PTL - RHO Squdron - Stress - SLAM

### ISSUE THREAD

**Issue by BobaRick** [baranidlo/bench#5]
I ran a couple RHO Squadron GUNBOATs with Push the Limit on them, and they received the stress on the first action - when the only available actions were Focus and SLAM.  I selected the Focus action and immediately received a stress token.  I'm guessing it has something to do with SLAM not being available as a free action.  

Once the GUNBOATs got closer and could Target Lock, they worked correctly.

**Comment by baranidlo** [comment]
Thanks for the bug reports, will look at them as soon as time permits.

**Comment by Sleet01** [comment]
I recently saw a similar issue on a Lothal Rebel with Experimental Interface installed.  I'd guess it's related.

**Comment by Sleet01** [comment]
Well, I tested 3x Rho + PTL, 1 x Rho + EI + Daredevil against this same list run by the computer, and I didn't see any extraneous stress from any of the available actions.  PTL and EI did give stress appropriately when used.

I believe there is either another factor besides PTL / EI, or the underlying issue may have been fixed in another check-in.  Please keep an eye out and update the issue if you see this again.

**Comment by Sleet01** [comment]
Found it!  Some paths for skipping over selecting subsequent actions return "null", but some return an undefined value.  That should probably be cleaned up, but for right now I've added a check for "undefined" to PTL and EI.

**Comment by Sleet01** [comment]
I haven't seen this in my recent testing.  Closing for now; if some variation on this bug re-surfaces then we can file a new issue!
