### ISSUE TITLE
Lieutenant Karsabi's Ability

### ISSUE THREAD

**Issue by BobaRick** [baranidlo/bench#59]
Lieutenant Karsabi's ability isn't quite working.  He can take a stress token to discard a Weapons Disabled token.

As a workaround, I see the shortcut for adding stress, but is there a shortcut for adding/removing a Weapons Disabled token?

**Comment by baranidlo** [comment]
Yeah I think he's not implemented yet at all. But we'll start working on
the pilots quite soon..

**Comment by BobaRick** [comment]
Thanks!

Any shortcut for removing/added Weapons Disabled token?

**Comment by baranidlo** [comment]
I'm affraid not atm..

**Comment by Sleet01** [comment]
~~Currently there doesn't appear to be a Weapons Disabled token.  I'm looking into what's involved in adding a new token; we need TTF font editing tools at the very least.~~

It would be easier for me to avoid making stupid comments if I knew that the original dev hated to call things by their actual names.  Weapons Disabled tokens are, of course, in the game already; they're just called ".Noattack" tokens.  Because... why!?

Anyhow, latest PR has a preliminary Weapons Disabled add/remove hotkey setup.  Once it's merged, `<alt>+<7>` will trigger Weapons Disabled on the selected ship, and `<shift>+<alt>+7` will remove it.

**Comment by Sleet01** [comment]
Also added Lt. Karsabi, since we now have the functions to make it simple.

**Comment by BobaRick** [comment]
Thanks!

**Comment by BobaRick** [comment]
Hi, I just tried to play Lt. Karsabi and his ability isn't working.  When he gets a Weapons Disabled token there's no way for him to discard it, and he should be able to do that by taking a stress token.

**Comment by Sleet01** [comment]
Weird.  Let me double-check that...

Edit: It's working on the devel code.  The PR containing this fix was pulled into the development branch but has not made it to the release version yet.  Please try again once the next release update happens.  Thanks!

**Comment by Sleet01** [comment]
This should be working correctly on release now.
