### ISSUE TITLE
Synced Turret & Intensity missing

### ISSUE THREAD

**Issue by cbmainz** [baranidlo/bench#61]
Synced Turret & Intensity missing from the TIE Aggressor Expansion Pack is missing.

I would add them myself, but I don't know how. Which files have to be edited?

**Comment by Sleet01** [comment]
Synced Turret is now in the devel branch Pull Request, seems to work fine.  It will be a while before it's in the release branch but I hope you can test it out when the release branch gets updated.

I'll see if I can work on Intensity in the next couple of days.

**Comment by Sleet01** [comment]
By the way, you can look at the current Pull Request and peruse the file diffs to see which changes required changing which files, if you are interested in working on the game!

**Comment by cbmainz** [comment]
Thanks. I will try the devel branch. 

And I have a look in the Pull Request how changes are made. I'm also not a programer but maybe some little things I can do.

**Comment by Sleet01** [comment]
Unfortunately, to run the devel code you will need to either:

1) fork the devel branch to your own GitHub repo as "master" or "gh-pages" and turn on GitHub's web hosting feature, or

2) clone the devel branch to your own computer and run it in an IDE like NetBeans or Visual Studio.

These aren't super-difficult tasks but they're a bit time-consuming.  Then again, if you can get it to work, you're halfway to being a fully-fledged web developer already :)

I'd say the biggest help non-programmers can provide is to fly lists and write new issues anytime there's a bug; that gives us guidance on what people are using and what the biggest problems are.

**Comment by cbmainz** [comment]
So, here two issues I have:

1. The pilot ability of 'Double Edge' seems not to work. When the first attack fails, there is no second attack possible.
2. After Advanced SLAM from Alpha-class Star Wing, when bumping into another ship the Alpha-class Star Wing gets still an action.

**Comment by Sleet01** [comment]
Thanks!  I'll take a look.

**Comment by Sleet01** [comment]
Double Edge is now in the PR, along with a fix for Advanced Slam ignoring collisions and obstacles.

**Comment by cbmainz** [comment]
I installt your devel branch on my server (just some webspace with some extras) and now 'Synced Turret' and 'Double Edge' works now. The fix for Advanced Slam works.

I have more issues, but I put them in a different threat.

**Comment by baranidlo** [comment]
Thanks, that's awesome.

We have currently limited time for testing, so if you can help us testing
in devel branch before the changes are released, that would be a huge help
:)

On Feb 23, 2018 13:19, "cbmainz" <notifications@github.com> wrote:

I installt your devel branch on my server (just some webspace with some
extras) and now 'Synced Turret' and 'Double Edge' works now. The fix for
Advanced Slam works.

I have more issues, but I put them in a different threat.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/baranidlo/bench/issues/61#issuecomment-367994589>, or mute
the thread

**Comment by Sleet01** [comment]
These two cards, at least, are working.
