### ISSUE TITLE
Squad points do not match

### ISSUE THREAD

**Issue by cbmainz** [baranidlo/bench#64]
I'm testing a list of a friend. He reported that the squad points do not match. Some upgrade cards do not have the right cost and are different in german and in english (s. pictures).

Here ist the List in [Yet Another Squad Builder](https://x-wing.crowdapp.de/?f=Scum%20and%20Villainy&d=v4!s!135:197,243,128:54:25:M.7,M.26;265:136:55:15:T.16,U.36,U.-1;212:18,-1:43:15:&sn=Unnamed%20Squadron&obs=).

<img width="1010" alt="scum-list-en" src="https://user-images.githubusercontent.com/3431649/36596304-8528795e-18a5-11e8-83d4-0550e3dabdfb.png"><img width="1010" alt="scum-list-de" src="https://user-images.githubusercontent.com/3431649/36596305-85481354-18a5-11e8-8543-68ebf9cdf6cc.png">

**Comment by baranidlo** [comment]
This should be not related to language, but to the order on which cards
were added to the ship.

Vaksai title always needs to be added first in order dor the discount to be
applied correctly.

This is a limitation of the builder code, and would be too much work to
improve at this moment.

Can you try to test german version, but add Vaksai first? Thx.

Btw I think we are missing translations for the newer cards, so if you
speak German, feel free to add them :)

On Feb 23, 2018 14:30, "cbmainz" <notifications@github.com> wrote:

I'm testing a list of a friend. He reported that the squad points do not
match. Some upgrade cards do not have the right cost and are different in
german and in english (s. pictures).

Here ist the List in Yet Another Squad Builder
<https://x-wing.crowdapp.de/?f=Scum%20and%20Villainy&d=v4!s!135:197,243,128:54:25:M.7,M.26;265:136:55:15:T.16,U.36,U.-1;212:18,-1:43:15:&sn=Unnamed%20Squadron&obs=>
.

[image: scum-list-en]
<https://user-images.githubusercontent.com/3431649/36596304-8528795e-18a5-11e8-83d4-0550e3dabdfb.png>[image:
scum-list-de]
<https://user-images.githubusercontent.com/3431649/36596305-85481354-18a5-11e8-8543-68ebf9cdf6cc.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/baranidlo/bench/issues/64>, or mute the thread

**Comment by cbmainz** [comment]
Okay, great, this works fine if I add Vaksai first. 

<img width="1010" alt="scum-list-de-v2" src="https://user-images.githubusercontent.com/3431649/36597064-3d9589ee-18a8-11e8-9435-01cf80f7e201.png">

I try to do some german translations.

**Comment by baranidlo** [comment]
Fantastic, thanks :)

**Comment by cbmainz** [comment]
@baranidlo german translation for pilots wave 11-13 is on its way …

Maybe late I will do the upgrade cards.
