### ISSUE TITLE
4-Lom  crew to deny an Evade token does not prevent the AI from using Evade tokens anyway

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#76]

**Comment by Sleet01** [comment]
...because there was a copy-paste error: the modifier was checking if the target had any *focus* tokens, even when trying to prevent evade token use, so 4-Lom would basically only prevent TIE/x7 pilots and PTL aces from using Evade tokens.  Focus use prevention worked fine though.

This is fixed in the latest PR.

**Comment by Sleet01** [comment]
The fix for this issue is now in Release (gh-pages); closing.
