### ISSUE TITLE
Thweek was given 0 evade dice in this attack from Wedge while suffering a structural damage

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#79]
![image](https://user-images.githubusercontent.com/8730661/36882400-9878f58c-1da1-11e8-8f3c-ed9ed21a892e.png)

**Comment by Sleet01** [comment]
No tests yet, but I'd guess that Wedge's ability wraps every defense dice calculation and that Structural Damage *adds* another check (so Wedge's ability applies twice during the attack).

**Comment by Sleet01** [comment]
In fact it appears to have been weirder still: since a number of pilots got double-initialized in an attempt to make sure that every dockable ship was getting detected, Wedge was probably double-wrapping the getagility() function of his targets.  That likely took the final agility of Thweek to zero.  I've made some refinements in how we initialize dockable ships that *should* fix this issue.
