### ISSUE TITLE
The game softlocked here. No fire button appears

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#89]
![image](https://user-images.githubusercontent.com/8730661/37156284-a7423b70-22b3-11e8-829b-8a7148d0d0ca.png)

My best guess is AI first order vanguard not knowing what to do if it doesn't need to spend

**Comment by Sleet01** [comment]
In cases where the game soft-locks, in the absence of any explicit errors, please try opening up the Developer's Console and seeing if there is an error message logged.  On Firefox, this is done via the key combo  \<ctrl\>+\<shift\>+\<k\>.   

If there *is* an error message (most likely an unhandled exception) please post it with the bug.  Unfortunately the exceptions for the release code are especially cryptic because they're reporting on minified code ("'d.a' is not a function" instead of "'self.isactive' is not a function") but it gives us some clues about the problem.

If there *isn't* an error message, it usually indicates an action queue screwup, so that is also helpful to know.

Thank again for all your help!

**Comment by boredompwndu** [comment]
![image](https://user-images.githubusercontent.com/8730661/37231398-0684755c-23b9-11e8-848d-bb693280b58f.png)

Luckily this is an easily reproducible softlock

**Comment by Sleet01** [comment]
Nice!  And, dammit, I'm 99% certain I put that code in.

**Comment by Sleet01** [comment]
Fixed in my current branch.  Unfortunately I haven't got a PR in yet, but once I have all the list parsing stuff fixed it'll all be submitted together.

**Comment by boredompwndu** [comment]
List parsing will make you my hero. Benchmark has been a super easy way to supplement prepping for worlds

**Comment by Sleet01** [comment]
This *should* be fixed in Release now.  Closing.
