### ISSUE TITLE
intimidation gets really excited when a ships run into the equipped ship

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#95]
![image](https://user-images.githubusercontent.com/8730661/37235913-bd5c4b3a-23d0-11e8-8445-49112e34f678.png)

**Comment by boredompwndu** [comment]
also the ship panel doesn't get updated when the ships are no longer in contact

![image](https://user-images.githubusercontent.com/8730661/37235931-e4613722-23d0-11e8-9724-97e5a0ed871a.png)

**Comment by Sleet01** [comment]
This should be a relatively simple fix.  I'll take a look today or tomorrow.

**Comment by Sleet01** [comment]
I need to read the code before I open my fat yap!  This was a little more complicated than expected, because by moving from a Unit.prototype.wrap_after() approach to an event listener approach meant doubling up on possible notifications: either A) the Intimidation carrier collides with an enemy, or B) an enemy collides with the Intimidation carrier.

Be that as it may, I think I've got it working correctly now.  There may be a bit of performance hit as the event listener will be triggered every time a *possible* collision occurs: it will be called whenever an AI ship is planning its possible moves, *or* when a ship actually executes its move.  But now only ships that are actually involved in a collision during the Activation or Combat phases will get a wrap_after() call, so this should still be more performant than the previous version.

**Comment by Sleet01** [comment]
Fix is now in Release; closing.
