### ISSUE TITLE
Deleting saved squads does not persist between games

### ISSUE THREAD

**Issue by boredompwndu** [baranidlo/bench#97]

**Comment by Sleet01** [comment]
This is a problem exacerbated, if not directly caused, by the old and buggy parsing code.  Two actions happen when the user clicks "delete": 1) the row entry is removed, and 2) the list is re-parsed, processed, and output as a key value.  If a saved list with that key value is *found*, it is deleted.  But many times the saved list and the key value do not match because the processing is bad.  This means that the saved list is ultimately not deleted, just removed from the list of squads until the next time the page refreshes.

My plan is to normalize all list interactions on the JSON representation, so that generating e.g. HTML-formatted Human-Readable strings, or ASCII (for replays), or key values (for saving squads) are 100% deterministic.  So far about half of this is working in my feature branch, so stay tuned.

**Comment by Sleet01** [comment]
This *should* be fixed in the devel branch after the parsing fixes are pulled in.
No idea on ETA.

**Comment by Sleet01** [comment]
This should be fixed in the current release version.  Here's what's going on under the hood:

1) the first time the user opens up v0.99.9.1, all of their local save info is read in by the new parser.
2) each list is either parsed into the new format, or fails to be parsed.
3) if parsed into the new format, that list is saved back in the new format.
4) old lists are deleted.
5) new-format versions of the old lists are displayed.

This ensures that as many old lists are saved as possible, but that the delete buttons work correctly because each list can be reliably addressed by the new name it has generated for itself.

I'll close this bug, but please open a new one if similar issues occur.
